project:
  type: website
  pre-render:
    - _extensions\astrodimitrios\carpentries\create-aio-file.lua
    - _extensions\astrodimitrios\carpentries\create-profiles-file.lua
    - _extensions\astrodimitrios\carpentries\nav.lua
    - _extensions\astrodimitrios\carpentries\more.lua
  render:
    - index.*
    - episodes/*
    - learners/*
    - "!learners/setup.md"
    - instructors/*
    - profiles/*
  post-render:
    - bash _extensions\astrodimitrios\carpentries\post-process-html.sh

carpentries:
  source: https://github.com/MetOffice/git-novice
  branch: main
  contact: d.theodorakis@metoffice.gov.uk
  license: CC-BY 4.0
  citation: CITATION.cff
  carpentry: cp
  carpentry_name: Carpentries
  carpentry_icon: carpentries
  life_cycle: stable
  created: '2023-08-04'
  keywords: software, data, lesson, The Carpentries, Git, GitHub
  episodes:
    - 01-basics.qmd
    - 02-setup.md
    - 03-create.md
    - 09-branches.qmd
    - 04-changes.qmd
    - 05-history.md
    - 06-reverting-changes.md
    - 06-ignore.md
    - Break.qmd
    - 07-github.md
    - 08-github-interface.md
    - 09-github-history.md
    - 10-pull-requests.md
    - 11-configuring-github.md
    - End.qmd
    - 10-open.md
    - 11-licensing.md
    - 12-citation.md
    - 13-hosting.md
    - 14-supplemental-rstudio.md
  # Information for Learners
  resources: True
  learners:
    - reference.md
    - discuss.md
    - fcm-git_cheat_sheet.md
    - repo-quick-start.md
  # Information for Instructors
  instructors:
    - instructor-notes.md
  profiles:
    - learner-profiles.md

website:
  title: "Version Control with Git"
  site-url: "https://metoffice.github.io/git-novice/"

format:
  carpentries-html

metadata-files:
  - _extensions\astrodimitrios\carpentries\translate.yml